### PR TITLE
Effects O modifier like OCL

### PR DESCRIPTION
**Pull request by rogervinc**
Add O modifer to effect parsing (alongside HTQ). The O modifier acts in the same way as the H modifier but will round the value (math.ceil) rather than truncate it (math.floor). This allows an effect like Holy Vindicator - Vindicator's Shield to be coded where the bonus is equal to the number of Channel Energy dice of the character and those dice go up on odd levels.
e.g. for a character that is Cleric 9 / Holy Vindicator 4 their effective level for channel energy is 13 which gives 7d6. [HCL] would give an incorrect modifier of 6, this [OCL] change would give a correct modifier of 7.  Other variant of HCL effects like '0.5 HCL' or '1 HCL' also do not consistently give the correct result, some are correct for odd CLs and wrong for even CLs and vice versa.

### CODE REVIEW

**Comment by Kelrugem** [comment]
Thank you :) 

As in the forums: E.g. speaking of an AC effect, then **AC: [CL], [-HCL]** (or **AC: [CL]; AC: [-HCL]** if the conglomerated one doesn't work) should work instead and always give the half but rounded up :) Because every natural number is the sum of "its half rounded down + its half rounded up" :) So, one can solve this for "half rounded up" which is then (roughly depicted) "CL - (Half of CL rounded down)" basically, and this formula is doable then in FG :) (so, I basically just replaced the rounded up version of the half of CL with a formula containing summands existing in FG)

Let me know whether this works for you :)

**Comment by Kelrugem** [comment]
But I can still think about adding it, because it may be easier to use your approach than coming up with my approach :) 

Thanks again, I appreciate that you took your time to look at this :) I am always happy about suggestions for the code :)

**Comment by bmos** [comment]
If this does get added to code it might be better to add a "round up" syntax rather than just doing it for half.
Something like [^HCL] to round up and [HCL] to round down.

**Comment by Kelrugem** [comment]
Thanks, Bmos, this is a good point :)

**Comment by rogervinc** [comment]
Updated code with a '^' modifier rather than 'O' as per bmos comment

**Comment by bmos** [comment]
> Updated code with a '^' modifier rather than 'O' as per bmos comment

Nice! I submitted a pull request to this pull request https://github.com/rogervinc/Extended-automation-and-overlays/pull/1

EDIT: apparently the original approach is justified. Please disregard this.

**Comment by bmos** [comment]
unfortunately your last commit regresses other code

**Comment by rogervinc** [comment]
> unfortunately your last commit regresses other code

Yes - I've got too many copies of code in different folders at the moment.  Should be correct now

**Comment by Kelrugem** [comment]
Uiui, a lot going on here :D Thanks a lot for your help :) I will try to soon look at this :) Some people even asked/requested some other features for parsing stuff like this; so, I may combine these requests with your code :)

**Comment by Kelrugem** [comment]
Hi :)

Just a short notice from me: I did not forget this pull request, I am just very busy right now because of my imminent move to Taipei :)

**Comment by Kelrugem** [comment]
I am now about merging this PR, sorry for the biiiig delay :D Thank you very much, I will just adjust the code slightly :)

**Pull request merged**
