### PR TITLE
Reimplement ActionAttackKel

### PR DESCRIPTION
**Pull request by bmos**
In theory, this should do all the same stuff with a lot less code and overwriting functions.

I know that handleApplyAoO and getRoll work and the code in modAttack worked in the tests I did.
onAttack, onAttackResolve, and onMissChance are unchanged.

The only thing I was unable to test is the alternate method of getting tags into various sub-functions via rActor.tags. I'm just not familiar enough with tags in attacks (since I mostly just used them for saving throws vs various schools).

Eliminating the extra rRoll.tags argument for many functions was critical to having modAttack call the prior function (which should be beneficial for compatibility), but could be rolled back by just replacing modAttack with the version you had before and not having it call modAttack_old.

I would recommend some thorough testing, as I don't know all the details of the features of your extension.

### CODE REVIEW

**Comment by Kelrugem** [comment]
thanks a lot for looking at this and spending time on this effort :) I really appreciate this, and I hope I will be able to look at it sooner than later :)

**Comment by bmos** [comment]
Just wanted to get this on your radar in case it has fallen off.
For now, it's still compatible with your latest updates.

**Comment by bmos** [comment]
I brought this back into parity with ../../tree/main

**Comment by bmos** [comment]
One thing to consider is that I'm embedding rRoll.tags into rSource.
It may be better to reimplement tags in such a way that rSource contains source tags and rTarget contains target tags.

**Comment by Kelrugem** [comment]
Indeed, a smoother approach doing it like that :) I will do so once I have a bit more time :) Thanks for the suggestion :)

**Comment by Kelrugem** [comment]
Thanks again for the this PR, sorry that it takes me so long to implement it; I hope you do not feel disappointed :)

**Comment by bmos** [comment]
That's ok, hopefully it's still accessible. I forgot about it when I was cleaning up my repos list!

**Pull request closed without merging**
