### PR TITLE
Fix Combat Tracker

### PR DESCRIPTION
**Pull request by bmos**
* ct_client.xml was not listed in extension.xml, so I removed it
* aoo and maxaoo fields need to be in ct_section_defense, so I moved them there
* the windowclass scripts didn't seem to be doing anything anymore, so I removed them
* I couldn't  figure out any reason that you were overriding wounds and nonlethal, so I removed them

### CODE REVIEW

**Comment by bmos** [comment]
If there was some reason that the wounds and nonlethal fields were using ActionDamage.onDamage instead of ActionDamage.applyDamage, let me know and I can add that part back in.

**Comment by bmos** [comment]
The note you had left on that file said "KEL: Due to Fortification I have to change Drag&Drop to settle that in at an earlier position in the code"
But I didn't see anything there that looked related to fortification. If it was important that it use ActionDamage.onDamage instead of ActionDamage.applyDamage, let me know and I can add it back in.

**Comment by Kelrugem** [comment]
Thank you :)

Actually, I already removed these files in the last update; were they still there? They were legacy from StrainInjury (accidentally copied over :D)

About the wound and nonlethal stuff: Would be good if you add it back, thanks :) The reason is that due to Fortification the code looks different and therefore I had to apply the drag&drop different, there were otherwise some things not working and errors were thrown :) (but I can check again if these problems still persist) Regarding nonlethal I also added some little feature I think (like the damage type? I am not sure anymore)

**Comment by Kelrugem** [comment]
Thank you very much, I really appreciate it :D

**Comment by bmos** [comment]
I think the nonlethal damage type thing is already there in 3.5E (at least it is now).
I have added those definitions back in 👍🏻

**Pull request merged**
